project_id = "shuzruoujtztngwzdffo"

[functions.analyse-location]
verify_jwt = false

[functions.enrich-demographics]
verify_jwt = false

[functions.ingest-satellite-data]
verify_jwt = false

[functions.satellite-webhook]
verify_jwt = false